url: "http://www.mandychen.me"
permalink: /blog/:title
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM #Github Flavored Markdown
  hard_wrap: false
  syntax_highlighter: rouge
gems:
  - jekyll-gist
